FROM ubuntu:latest

# Install SSH server and Ansible
RUN apt-get update && \
    apt-get install -y openssh-server && \
    apt-get install -y ansible && \
    apt-get clean

# Configure SSH
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    echo 'root:password' | chpasswd && \
    mkdir /var/run/sshd

# Expose SSH port
EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
